# Generated by Django 5.1.7 on 2025-03-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_category_description_forecast_projected_income_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecast',
            name='projected_expense',
        ),
        migrations.RemoveField(
            model_name='forecast',
            name='projected_income',
        ),
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='client',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
