# Generated by Django 5.1.7 on 2025-03-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_transaction_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecast',
            old_name='forecast_date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='forecast',
            name='start_date',
            field=models.DateField(default='2025-03-28'),
            preserve_default=False,
        ),
    ]
