# Generated by Django 5.1.7 on 2025-03-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_rename_forecast_date_forecast_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(default='Initial Data', max_length=255),
            preserve_default=False,
        ),
    ]
